### ISSUE TITLE
ldpred score error 2 

### ISSUE THREAD

**Issue by nandobonf** [bvilhjal/ldpred#101]
Dear authors,
when I run ldpred score on a test genotype I get the following error message. Could you please help me fixing this?
Thanks.

```
Calculating LDpred-inf risk scores
Parsing PLINK bed file: test.datasets/final.casecontrol
100.00%Traceback (most recent call last):
  File "/data/admin/NB.geno/ldpred/LDpred.py", line 300, in <module>
    main()
  File "/data/admin/NB.geno/ldpred/LDpred.py", line 293, in main
    validate.main(p_dict)
  File "/data/admin/NB.geno/ldpred/ldpred/validate.py", line 658, in main
    verbose=verbose, summary_dict=summary_dict)
  File "/data/admin/NB.geno/ldpred/ldpred/validate.py", line 412, in calc_risk_scores
    prs_dict = get_prs(bed_file, rs_id_map, phen_map, only_score=only_score, verbose=verbose)
  File "/data/admin/NB.geno/ldpred/ldpred/validate.py", line 148, in get_prs
    '\n'%(perc_missing*100)) 
TypeError: not all arguments converted during string formatting
```

**Comment by bvilhjal** [comment]
Thanks for the bug report..
