### ISSUE TITLE
issue with plink and score function

### ISSUE THREAD

**Issue by ishanparanjpe** [bvilhjal/ldpred#105]
I am trying to generate scores (last step) for a plink formatted genotype file. I am not interested in prediction accuracy and only want to output scores. 

`
nohup python $ldpred score --gf=$target_file --rf=$ldpred_output_file --out=$score_output_file --only-score  > $nohup_log &
`

When I run this, I get the following error:

> Calculating LDpred-inf risk scores
Parsing PLINK bed file: /sc/private/regen/data/Regeneron/GSA/imputed_tgp_p3_plink/GSA_chr_all
Traceback (most recent call last):
  File "/hpc/packages/minerva-centos7/ldpred/1.0.6/ldpred/LDpred.py", line 300, in <module>
    main()
  File "/hpc/packages/minerva-centos7/ldpred/1.0.6/ldpred/LDpred.py", line 293, in main
    validate.main(p_dict)
  File "/hpc/packages/minerva-centos7/ldpred/1.0.6/ldpred/ldpred/validate.py", line 658, in main
    verbose=verbose, summary_dict=summary_dict)
  File "/hpc/packages/minerva-centos7/ldpred/1.0.6/ldpred/ldpred/validate.py", line 412, in calc_risk_scores
    prs_dict = get_prs(bed_file, rs_id_map, phen_map, only_score=only_score, verbose=verbose)
  File "/hpc/packages/minerva-centos7/ldpred/1.0.6/ldpred/ldpred/validate.py", line 12, in get_prs
    plinkf = plinkfiles.plinkfile.PlinkFile(genotype_file)
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/plinkio/plinkfile.py", line 14, in __init__
    self.handle = cplinkio.open( path )
OSError: Error while trying to open the FAM plink file.

**Comment by bvilhjal** [comment]
Hi, 

I apologize slow reply on this.   You can use the --only-score

**Comment by May-Ibrahim** [comment]
Hi, I'm getting the same error although I'm using --only-score. I don't think the error is related to the use of only-score. It can't open the plink file although it is there.

Have you figured out how to fix it?

Thanks,
May
