### ISSUE TITLE
TypeError: float argument required, not numpy.ndarray 

### ISSUE THREAD

**Issue by Qinqiword** [bvilhjal/ldpred#107]
Hi,

I am using LDpred to calculate PRS socres, but encountered the following error.

```shell
$ python ${workdir}/LDpred.py --debug score --gf=${input1}/chr22  --rf=/home/chenf/WJ/PRS_20190807/Results_20190916/chr22  --out=${output}/chr22
=============================== LDpred v. 1.0.6 ================================

Parsed parameters:
{'gf': '/home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22', 'r2': [1, 0.2], 'f': [1, 0.3, 0.1, 0.03, 0.01, 0.003, 0.001], 'pf_format': 'STANDARD', 'ldpred_action': 'score', 'rf_format': 'ANY', 'p': [1, 0.3, 0.1, 0.03, 0.01, 0.003, 0.001, 0.00030000000000000003, 0.0001, 3.0000000000000004e-05, 1e-05, 1e-06, 1e-07, 1e-08], 'rf': '/home/chenf/WJ/PRS_20190807/Results_20190916/chr22', 'only_score': False, 'pf': None, 'pcs_file': None, 'debug': True, 'cov_file': None, 'split_by_chrom': False, 'out': '/home/chenf/WJ/PRS_20190807/Results_20190916/chr22'}
Parsing phenotypes
/home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22.fam
Parsing Phenotypes
Parsed 2641 phenotypes successfully

Calculating P+T risk scores using p-value threshold of 1.000e+00, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0295
Current PRS r2: 0.0009
PRS correlation: -0.0295
[0.00086846]
Variance explained (Pearson R2) by PRS: 0.0009
The slope for predictions with weighted effects is: -0.0740
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p1.0000e+00.txt

Calculating P+T risk scores using p-value threshold of 3.000e-01, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0207
Current PRS r2: 0.0004
PRS correlation: -0.0207
[0.00042826]
Variance explained (Pearson R2) by PRS: 0.0004
The slope for predictions with weighted effects is: -0.1265
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p3.0000e-01.txt

Calculating P+T risk scores using p-value threshold of 1.000e-01, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0170
Current PRS r2: 0.0003
PRS correlation: -0.0170
[0.00028766]
Variance explained (Pearson R2) by PRS: 0.0003
The slope for predictions with weighted effects is: -0.0624
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p1.0000e-01.txt

Calculating P+T risk scores using p-value threshold of 3.000e-02, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0050
Current PRS r2: 0.0000
PRS correlation: -0.0050
[2.5451254e-05]
Variance explained (Pearson R2) by PRS: 0.0000
The slope for predictions with weighted effects is: -0.0126
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p3.0000e-02.txt

Calculating P+T risk scores using p-value threshold of 1.000e-02, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0032
Current PRS r2: 0.0000
PRS correlation: -0.0032
[9.98078909e-06]
Variance explained (Pearson R2) by PRS: 0.0000
The slope for predictions with weighted effects is: -0.0148
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p1.0000e-02.txt

Calculating P+T risk scores using p-value threshold of 3.000e-03, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: 0.0051
Current PRS r2: 0.0000
PRS correlation: 0.0051
[2.56714936e-05]
Variance explained (Pearson R2) by PRS: 0.0000
The slope for predictions with weighted effects is: 0.0958
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p3.0000e-03.txt

Calculating P+T risk scores using p-value threshold of 1.000e-03, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0208
Current PRS r2: 0.0004
PRS correlation: -0.0208
[0.00043173]
Variance explained (Pearson R2) by PRS: 0.0004
The slope for predictions with weighted effects is: -0.0437
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p1.0000e-03.txt

Calculating P+T risk scores using p-value threshold of 3.000e-04, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0257
Current PRS r2: 0.0007
PRS correlation: -0.0257
[0.00065826]
Variance explained (Pearson R2) by PRS: 0.0007
The slope for predictions with weighted effects is: -0.1354
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p3.0000e-04.txt

Calculating P+T risk scores using p-value threshold of 1.000e-04, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0260
Current PRS r2: 0.0007
PRS correlation: -0.0260
[0.00067831]
Variance explained (Pearson R2) by PRS: 0.0007
The slope for predictions with weighted effects is: -0.2441
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p1.0000e-04.txt

Calculating P+T risk scores using p-value threshold of 3.000e-05, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0202
Current PRS r2: 0.0004
PRS correlation: -0.0202
[0.00040707]
Variance explained (Pearson R2) by PRS: 0.0004
The slope for predictions with weighted effects is: -0.1441
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p3.0000e-05.txt

Calculating P+T risk scores using p-value threshold of 1.000e-05, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0229
Current PRS r2: 0.0005
PRS correlation: -0.0229
[0.00052233]
Variance explained (Pearson R2) by PRS: 0.0005
The slope for predictions with weighted effects is: -0.5336
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p1.0000e-05.txt

Calculating P+T risk scores using p-value threshold of 1.000e-06, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
Current PRS correlation: -0.0245
Current PRS r2: 0.0006
PRS correlation: -0.0245
[0.0005999]
Variance explained (Pearson R2) by PRS: 0.0006
The slope for predictions with weighted effects is: -1.3791
Writing polygenic scores to file /home/chenf/WJ/PRS_20190807/Results_20190916/chr22_P+T_p1.0000e-06.txt

Calculating P+T risk scores using p-value threshold of 1.000e-07, and r2 threshold of 0.20
Parsing PLINK bed file: /home/chenf/WJ/PRS_20190807/CAS_QC_data/chr22
2641 individuals have phenotype and genotype information.
Iterating over BED file to calculate risk scores.
DONE!
Number of non-matching NTs: 0
Number of flipped NTs: 0
/home/chenf/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:2400: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/chenf/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:2401: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
Current PRS correlation: nan
Current PRS r2: nan
PRS correlation: nan
[]
Traceback (most recent call last):
  File "/home/chenf/WJ/PRS_20190807/ldpred/LDpred.py", line 300, in <module>
    main()
  File "/home/chenf/WJ/PRS_20190807/ldpred/LDpred.py", line 293, in main
    validate.main(p_dict)
  File "/home/chenf/WJ/PRS_20190807/ldpred/ldpred/validate.py", line 711, in main
    verbose=verbose, summary_dict=summary_dict)
  File "/home/chenf/WJ/PRS_20190807/ldpred/ldpred/validate.py", line 454, in calc_risk_scores
    print('Variance explained (Pearson R2) by PRS: %0.4f' % pred_r2)
TypeError: float argument required, not numpy.ndarray
```

I modified the `validate.py` to print out the `pred_r2` and it was empty before throwing this error.

Do you have any ideas about this? Sorry if this quetion is too obvious. I am new to this area.

Bests,
Jing

**Comment by bvilhjal** [comment]
It looks like the SNPs in the bed file might have allele freq of 0/1, I suggest try to filter those out before using ldpred score.

I hope that helps.

Best,
Bjarni
