### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by KClaudio21** [bvilhjal/ldpred#123]
I am getting the error below. I was told that the program was trying to load a serialized object from
disk and possibly encountered a corrupted object (an emty input file), but I was able to do the previous step (generate the coord file) and it has data (>200Kb). Do you have any ideas about why I coming across this error?

Traceback (most recent call last):
  File "/apps/python3/3.6.5/bin/ldpred", line 10, in <module>
    sys.exit(main())
  File "/apps/python3/3.6.5/lib/python3.6/site-packages/ldpred/run.py", line 337, in main
    main_with_args(sys.argv[1:])
  File "/apps/python3/3.6.5/lib/python3.6/site-packages/ldpred/run.py", line 323, in main_with_args
    LDpred_gibbs.main(p_dict)
  File "/apps/python3/3.6.5/lib/python3.6/site-packages/ldpred/LDpred_gibbs.py", line 413, in main
    ld_dict = ld.get_ld_dict_using_p_dict(p_dict, summary_dict)
  File "/apps/python3/3.6.5/lib/python3.6/site-packages/ldpred/ld.py", line 247, in get_ld_dict_using_p_dic
t
    summary_dict=summary_dict)
  File "/apps/python3/3.6.5/lib/python3.6/site-packages/ldpred/ld.py", line 318, in get_ld_dict
    ld_dict = _load_ld_info_(local_ld_dict_file, verbose=verbose, compressed=compressed)
  File "/apps/python3/3.6.5/lib/python3.6/site-packages/ldpred/ld.py", line 436, in _load_ld_info_
    ld_dict = pickle.load(f)
EOFError: Ran out of input

**Comment by bvilhjal** [comment]
Hi, I apologize for the slow reply on this issue.

I suspect that you only need to delete the LD file, and re-run LDpred.  Try deleting the file that starts with the prefix that you provided in the --ldf flag when running ldpred gibbs.

Best,
Bjarni
