### ISSUE TITLE
The posterior mean is not a real number?

### ISSUE THREAD

**Issue by BeatrizCortes** [bvilhjal/ldpred#125]
Hello, 

I am trying to use LDPred for my analysis and I found some problems, I wonder if you can help me with that.

First of all, I wanted to say I am using exonic data from 135 genes, in total 5000 SNPs. I have the bed/bim/fam files and also the summary statistics. I have some missing genotypes in the PLINK files so the N is not the same in all the SNPs. There you have the header of my ss file:

_CHR    POS    RS    REF    ALT    REFFREQ    PVAL    BETA    SE    N
1    17345493    rs147408869:17345493:G:A    G    A    0.999750248253493    0.981648    -0.0521315403543972    2.26627    4008
1    17354297    1:17354297_A_G    A    G    0.99226871257485    0.513682    0.255200202206527    0.390748    4008
1    17355075    1:17355075_A_T    A    T    0.996901322355289    0.730458    -0.272714645329994    0.791587    4008
1    17355218    rs11541235:17355218:A:G    A    G    0.99849750499002    0.362263    -1.71577112322872    1.88327    4008
1    17355353    1:17355353_C_G    C    G    0.999632243013972    0.87206    0.378066504290352    2.34762    4008_

I found no problems to use the coord, inf and score commands. But with my data the gibbs and p+t commands do not work. 

I used the following lines to call ### gibbs:

> ldpred gibbs --cf /***/***/***/***/***/LDPRED/1_coord/coord_file --ldr 50 --ldf /***/***/***/***/***/LDPRED/2_gibbs/ldf --out /***/***/***/***/***/LDPRED/2_gibbs/gibbs_50ldr

**And I obtain the following:**
_=============================== LDpred v. 1.0.8 ================================

Applying LDpred with LD radius: 50
1573 SNP effects were found
/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/ld.py:365: ComplexWarning: Casting complex values to real discards the imaginary part
  summary_dict[1.11]={'name':'Genome-wide (LDscore) estimated heritability:','value':'%0.4f'%gw_h2_ld_score_est}
/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/ld.py:366: ComplexWarning: Casting complex values to real discards the imaginary part
  summary_dict[1.12]={'name':'Chi-square lambda (inflation statistic).','value':'%0.4f'%chi_square_lambda}
Calculating LDpred-inf weights
/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_inf.py:48: ComplexWarning: Casting complex values to real discards the imaginary part
  updated_betas[start_i: stop_i] = sp.dot(A_inv * n , beta_hats[start_i: stop_i])  # Adjust the beta_hats
Starting LDpred gibbs with f=1.0000
/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py:68: ComplexWarning: Casting complex values to real discards the imaginary part
  rv_scalars[i]=sampl_var_shrink_factor* sp.sqrt((hdmp_hdmpn_i) * (1.0 / ni))
/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py:166: ComplexWarning: Casting complex values to real discards the imaginary part
  curr_post_means[snp_i] = cd['hdmp_hdmpn'] * postp * res_beta_hat_i
/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py:176: ComplexWarning: Casting complex values to real discards the imaginary part
  curr_betas[snp_i] = proposed_beta  # UPDATE BETA
30.00%Sum of squared updated effects estimates seems too large: 0.0275
This suggests that the Gibbs sampler did not convergence.
100.00%
/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py:375: ComplexWarning: Casting complex values to real discards the imaginary part
  f.write('%s    %d    %s    %s    %s    %0.4e    %0.4e\n' % (chrom, pos, sid, nt1, nt2, raw_beta, ldpred_beta))
Starting LDpred gibbs with f=0.3000
30.00%Sum of squared updated effects estimates seems too large: 0.1672
This suggests that the Gibbs sampler did not convergence.
100.00%
Starting LDpred gibbs with f=0.1000
30.00%Sum of squared updated effects estimates seems too large: 0.8202
This suggests that the Gibbs sampler did not convergence.
55.00%/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py:160: RuntimeWarning: overflow encountered in cdouble_scalars
  postp = numerator / (numerator + d_const_b2_exp)
/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py:160: RuntimeWarning: invalid value encountered in cdouble_scalars
  postp = numerator / (numerator + d_const_b2_exp)
Traceback (most recent call last):
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/bin/ldpred", line 10, in <module>
    sys.exit(main())
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/run.py", line 331, in main
    main_with_args(sys.argv[1:])
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/run.py", line 317, in main_with_args
    LDpred_gibbs.main(p_dict)
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py", line 407, in main
    verbose=p_dict['debug'], summary_dict=summary_dict)
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py", line 316, in ldpred_genomewide
    print_progress=False)
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LDpred_gibbs.py", line 161, in ldpred_gibbs
    assert sp.isreal(postp), 'The posterior mean is not a real number?  Possibly due to problems with summary stats, LD estimates, or parameter settings.' 
AssertionError: The posterior mean is not a real number?  Possibly due to problems with summary stats, LD estimates, or parameter settings._

I used the following lines to call ### p+t:

> ldpred p+t --cf /***/***/***/***/***/LDPRED/1_coord/coord_file --ldr 50 --out /***/***/***/***/***/LDPRED/2_p+t/p+t_50

### And I obtain the following:

_=============================== LDpred v. 1.0.8 ================================

0.00%/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LD_pruning_thres.py:175: ComplexWarning: Casting complex values to real discards the imaginary part
  f.write('%s    %d    %s    %s    %s    %0.4e    %0.4e    %0.4e    %0.4e\n'%(chrom, pos, sid, nt1, nt2, raw_beta, raw_pval_beta, upd_beta, upd_pval_beta))
21.43%Traceback (most recent call last):
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/bin/ldpred", line 10, in <module>
    sys.exit(main())
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/run.py", line 331, in main
    main_with_args(sys.argv[1:])
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/run.py", line 321, in main_with_args
    LD_pruning_thres.main(p_dict)
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LD_pruning_thres.py", line 212, in main
    run_pt(p_dict,summary_dict)
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LD_pruning_thres.py", line 196, in run_pt
    max_r2s=max_r2s)
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LD_pruning_thres.py", line 121, in ld_pruning
    max_ld=max_r2, verbose=verbose)
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/LD_pruning_thres.py", line 17, in ld_clumping
    pruning_vector = ld.smart_ld_pruning(pruning_stat, ld_table, max_ld=max_ld, verbose=verbose, reverse=True)    
  File "/software/debian-8/general/virtenvs/LDpred-py3.5/lib/python3.5/site-packages/ldpred/ld.py", line 217, in smart_ld_pruning
    l.sort(reverse=reverse)
TypeError: unorderable types: complex() < complex()_

**Do you know which one can be the problem with that? I am not sure why "inf" method words but not the other.**

Thanks in advance

Beatriz

**Comment by bvilhjal** [comment]
Hi Beatriz, 

Thanks for your question.  It's unclear to me what could cause this, but I suspect the LD calculation is somehow not working.  What LD reference are you using?  Do have some statistics on it, e.g. number of individuals, missing rates (for SNPs and individuals), etc.

Best,
Bjarni

**Comment by BeatrizCortes** [comment]
Hi Bjarni,

I am using as LD reference the same PLINK file as the one I use with coords command (the training subset of my data). I also try without any LD reference as in the help says "LD file (prefix). A path and filename prefix for the LD file. If it does not exist, it will be generated. This can take up to several hours, depending on LD radius used.", but still doesn't work. However, both options work correctly with the inf command. 

The data has some missing but it has less than 0.05 missing for SNPs and less than 0.1 missing for sample. The total genotyping rate obtained with PLINK is 0.995936. I also try to filter samples with less than 0.01 missing and it doesn't work, with a total genotyping rate in remaining samples equal to 0.997072.

Best regards and thank you in advance. 

Beatriz

**Comment by bvilhjal** [comment]
Hi Beatriz, 

Try installing LDpred 1.0.10 and re-run this.  I don't really know what is causing this, but 1.0.10 is a more stable release.

I hope that helps.

Best,
Bjarni

**Comment by XiaoweiHu-Stat** [comment]
I have the same issue for both ldpred gibbs and ldpred p+t. The issue for gibbs is "AssertionError: The posterior mean is not a real number?  Possibly due to problems with summary stats, LD estimates, or parameter settings."
The issue for p+t is "TypeError: '<' not supported between instances of 'complex' and 'complex'".
I have tried ldpred 1.0.10  and 1.0.11, and I have tried ldr=(10,50,100,500,1000,5000).

Can someone help me with these issues? Thank you.

**Comment by jenny1022** [comment]
I have the same issue for this step, I have tried ldpred gibbs in different chromosomes, what is interesting is it works in chr22 but gets issue in chr1. The issue for gibbs is "AssertionError: The posterior mean is not a real number?  Possibly due to problems with summary stats, LD estimates, or parameter settings."
I wonder if anyone has solved the problem? Thank you.

**Comment by ghost** [comment]
Problem persists for 1.0.10 as well: 

```
 Calculating SNP weights for Chromosome 5/usr/local/lib/python3.7/site-packages/ldpred/ld.py:353: ComplexWarning: Casting complex values to real discards the imaginary part
 print('%s heritability LD score estimate: %0.4f'% (chrom_str,chr_h2_ld_score_est))
 /usr/local/lib/python3.7/site-packages/ldpred/ld.py:362: ComplexWarning: Casting complex values to real discards the imaginary part
 print('Genome-wide lambda inflation: %0.4f'% chi_square_lambda)
 /usr/local/lib/python3.7/site-packages/ldpred/ld.py:364: ComplexWarning: Casting complex values to real discards the imaginary part
 print('LD-score estimated genome-wide heritability: %0.4f'% gw_h2_ld_score_est)
 /usr/local/lib/python3.7/site-packages/ldpred/ld.py:365: ComplexWarning: Casting complex values to real discards the imaginary part
 summary_dict[1.11]={'name':'Genome-wide (LDscore) estimated heritability:','value':'%0.4f'%gw_h2_ld_score_est}
 /usr/local/lib/python3.7/site-packages/ldpred/ld.py:366: ComplexWarning: Casting complex values to real discards the imaginary part
 summary_dict[1.12]={'name':'Chi-square lambda (inflation statistic).','value':'%0.4f'%chi_square_lambda}
 /usr/local/lib/python3.7/site-packages/ldpred/ld.py:375: ComplexWarning: Casting complex values to real discards the imaginary part
 print('Heritability used for inference: %0.4f'%h2)
 /usr/local/lib/python3.7/site-packages/ldpred/LDpred_inf.py:48: ComplexWarning: Casting complex values to real discards the imaginary part
 updated_betas[start_i: stop_i] = sp.dot(A_inv * n , beta_hats[start_i: stop_i])  # Adjust the beta_hats
 /usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py:55: ComplexWarning: Casting complex values to real discards the imaginary part
 rv_scalars[:]=sampl_var_shrink_factor* sp.sqrt((hdmp_hdmpn) * (1.0 / ldpred_n))
 /usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py:170: ComplexWarning: Casting complex values to real discards the imaginary part
 curr_post_means[snp_i] = cd['hdmp_hdmpn'] * postp * res_beta_hat_i
 /usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py:180: ComplexWarning: Casting complex values to real discards the imaginary part
 curr_betas[snp_i] = proposed_beta  # UPDATE BETA
 /usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py:390: ComplexWarning: Casting complex values to real discards the imaginary part
 f.write('%s    %d    %s    %s    %s    %0.4e    %0.4e\n' % (chrom, pos, sid, nt1, nt2, raw_beta, ldpred_beta))
 /usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py:164: RuntimeWarning: overflow encountered in cdouble_scalars
 postp = numerator / (numerator + d_const_b2_exp)
 /usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py:164: RuntimeWarning: invalid value encountered in cdouble_scalars
 postp = numerator / (numerator + d_const_b2_exp)
 
 Using the given fixed sample size of 7160
 Traceback (most recent call last):
 File "/usr/local/bin/ldpred", line 8, in <module>
 sys.exit(main())
 File "/usr/local/lib/python3.7/site-packages/ldpred/run.py", line 337, in main
 main_with_args(sys.argv[1:])
 File "/usr/local/lib/python3.7/site-packages/ldpred/run.py", line 323, in main_with_args
 LDpred_gibbs.main(p_dict)
 File "/usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py", line 422, in main
 sampl_var_shrink_factor=1, verbose=p_dict['debug'], summary_dict=summary_dict)
 File "/usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py", line 328, in ldpred_genomewide
 snp_lrld=snp_lrld, print_progress=False)
 File "/usr/local/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py", line 165, in ldpred_gibbs
 assert sp.isreal(postp), 'The posterior mean is not a real number?  Possibly due to problems with summary stats, LD estimates, or parameter settings.'
 AssertionError: The posterior mean is not a real number?  Possibly due to problems with summary stats, LD estimates, or parameter settings
```

**Comment by yingxi-kaylee** [comment]
> I have the same issue for both ldpred gibbs and ldpred p+t. The issue for gibbs is "AssertionError: The posterior mean is not a real number? Possibly due to problems with summary stats, LD estimates, or parameter settings."
> The issue for p+t is "TypeError: '<' not supported between instances of 'complex' and 'complex'".
> I have tried ldpred 1.0.10 and 1.0.11, and I have tried ldr=(10,50,100,500,1000,5000).
> 
> Can someone help me with these issues? Thank you.

I have the same issue. Did you figure out why?

**Comment by XiaoweiHu-Stat** [comment]
Haven't figured it out.
________________________________
