### ISSUE TITLE
KeyError during coord genotypes

### ISSUE THREAD

**Issue by pgormley** [bvilhjal/ldpred#131]
I'm having a problem running coordinate genotypes (between UKbb ref panel + sumstats + validation_genotypes).

Example run command:
```
ldpred coord --gf UKBB20_CEU_REF.merged.hm3_only \
        --ssf Alzheimers_Disease.sumstats \
        --N 54162 \
        --out MK.imp.plink.hardcalls.merged.hm3_only.Alzheimers_Disease.coord \
        --ssf-format BASIC \
        --only-hm3 \
        --vbim MK.imp.plink.hardcalls.merged.hm3_only.bim
```

Error message:
```
Traceback (most recent call last):
  File "/home/gormlepa/.local/bin/ldpred", line 10, in <module>
    sys.exit(main())
  File "/home/gormlepa/.local/lib/python3.7/site-packages/ldpred/run.py", line 380, in main
    main_with_args(sys.argv[1:])
  File "/home/gormlepa/.local/lib/python3.7/site-packages/ldpred/run.py", line 362, in main_with_args
    coord_genotypes.main(p_dict)
  File "/home/gormlepa/.local/lib/python3.7/site-packages/ldpred/coord_genotypes.py", line 625, in main
    debug=p_dict['debug'])
  File "/home/gormlepa/.local/lib/python3.7/site-packages/ldpred/coord_genotypes.py", line 506, in coordinate_datasets
    filter_coord_data(coord_data_dict, maf_filter)
  File "/home/gormlepa/.local/lib/python3.7/site-packages/ldpred/coord_genotypes.py", line 125, in filter_coord_data
    cd[k] = cd[k][filter_mask]
KeyError: 'raw_snps'
```

Any ideas why?

**Comment by fhormoz** [comment]
I have the same error. I am using 1000G PLINK files and existing summary statistics.

**Comment by bvilhjal** [comment]
Hi,

Thanks for the bug report.  This was caused by a change in v 1.0.11.  I will include an update in the next version (sometime in the coming days).  In the meantime I recommend you use version 1.0.10.

**Comment by AmberDeVries** [comment]
You can change line 121 in coord_genotypes.py (in a directory like "/usr/local/lib/python3.7/site-packages/ldpred/coord_genotypes.py") to:
data_keys = ['raw_snps_ref', 'snp_stds_ref', 'snp_means_ref', 'freqs_ref' ,'ps', 'ns', 'positions', 'nts', 'sids','betas','log_odds']
and then it should work.

**Comment by mahideel** [comment]
Hi, I also have the same error.  I tried modifying line 121 in coord_genotypes.py as suggested by Amber De Vries but still no luck. Exactly the same error. 

Would you know where I can download the version 1.0.10? 

Many thanks.

**Comment by bnj50** [comment]
I am getting the same error...any fix yet?

**Comment by ClaraAlbi** [comment]
You can install the 1.0.10 version like:

pip install -Iv ldpred==1.0.10

**Comment by wavefancy** [comment]
I had the sample issue with 1.0.11. But fixed by @AmberDeVries 's approach, modified line 121.

**Comment by jpattee** [comment]
Is there any update on when this error will be fixed? The current bug is essentially fatal to the program.
