### ISSUE TITLE
KeyError in ldpred fast

### ISSUE THREAD

**Issue by gulumk** [bvilhjal/ldpred#135]
Hi, 
I am getting the error below when trying to run ldpred fast. Do you have any suggestions how to troubleshoot the problem? 
Thanks! 

```
ldpred fast \
   --cf cad_coord_chr17_out \
   --ldr 2210 \
   --ldf cad_ld_chr17_out \
   --out cad_ldpred_chr17_fast_out \



=============================== LDpred v. 1.0.11 ===============================

Traceback (most recent call last):
  File "/usr/local/bin/ldpred", line 11, in <module>
    load_entry_point('LDpred==1.0.11', 'console_scripts', 'ldpred')()
  File "/usr/local/lib/python3.6/site-packages/LDpred-1.0.11-py3.6.egg/ldpred/run.py", line 380, in main
    main_with_args(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/LDpred-1.0.11-py3.6.egg/ldpred/run.py", line 366, in main_with_args
    LDpred_fast.main(p_dict)
  File "/usr/local/lib/python3.6/site-packages/LDpred-1.0.11-py3.6.egg/ldpred/LDpred_fast.py", line 202, in main
    eff_type = get_eff_type(p_dict['cf'])
  File "/usr/local/lib/python3.6/site-packages/LDpred-1.0.11-py3.6.egg/ldpred/LDpred_fast.py", line 190, in get_eff_type
    eff_type = df['parameters']['eff_type'][...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'parameters' doesn't exist)"
```

**Comment by bcrone** [comment]
I can second this error

**Comment by bnj50** [comment]
I am getting the same error

**Comment by Spendlove** [comment]
I am getting this error with both ldpred fast and ldpred gibbs and I can't figure out how to fix it.  One problem may be the fact that I don't have an actual file for --ldf.  The documentation says it calculates the LD for you though so this in theory should be ok...
