### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by chokriNao** [bvilhjal/ldpred#136]
Hi,
I encountered this issue when I tried to use ldpred coord using 1kg EUR as reference. I tried LDpred v. 1.0.8, 1.0.11 and the develop version and all threw the same error message.
the fallowing is returned by the develop version:

> Coordinating datasets (Summary statistics and LD reference genotypes).
13.04%Traceback (most recent call last):
  File "/usr/bin/ldpred", line 11, in <module>
    load_entry_point('LDpred==1.0.11', 'console_scripts', 'ldpred')()
  File "/usr/lib/python3.7/site-packages/ldpred/run.py", line 380, in main
    main_with_args(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/ldpred/run.py", line 362, in main_with_args
    coord_genotypes.main(p_dict)
  File "/usr/lib/python3.7/site-packages/ldpred/coord_genotypes.py", line 625, in main
    debug=p_dict['debug'])
  File "/usr/lib/python3.7/site-packages/ldpred/coord_genotypes.py", line 443, in coordinate_datasets
    reference_genotype_file, snp_indices)
  File "/usr/lib/python3.7/site-packages/ldpred/plinkfiles.py", line 41, in parse_plink_snps
    next_i = ordered_snp_indices.pop()
IndexError: pop from empty list

any help please!

**Comment by LuHaojie818** [comment]
I have got the same question with our test data, does anyone know what's wrong?

**Parsing summary statistics file: base/TOY_BASE_GWAS.assoc
100.00%
SS file loaded, now sorting and storing in HDF5 file.
Coordinating datasets (Summary statistics and LD reference genotypes).
4.17%Traceback (most recent call last):
  File "/mnt/luhaojie/.local/bin/ldpred", line 8, in <module>
    sys.exit(main())
  File "/mnt/luhaojie/.local/lib/python3.8/site-packages/ldpred/run.py", line 380, in main
    main_with_args(sys.argv[1:])
  File "/mnt/luhaojie/.local/lib/python3.8/site-packages/ldpred/run.py", line 362, in main_with_args
    coord_genotypes.main(p_dict)
  File "/mnt/luhaojie/.local/lib/python3.8/site-packages/ldpred/coord_genotypes.py", line 620, in main
    coordinate_datasets(p_dict['gf'], h5f,summary_dict,
  File "/mnt/luhaojie/.local/lib/python3.8/site-packages/ldpred/coord_genotypes.py", line 442, in coordinate_datasets
    raw_snps, freqs = plinkfiles.parse_plink_snps(
  File "/mnt/luhaojie/.local/lib/python3.8/site-packages/ldpred/plinkfiles.py", line 41, in parse_plink_snps
    next_i = ordered_snp_indices.pop()
IndexError: pop from empty list**

**Comment by OmegaPetrazzini** [comment]
Same error, did you find any solution?

**Comment by erez-odna** [comment]
getting same error, i'll be happy to know if anyone found a solution
