### ISSUE TITLE
Unable to open object (object 'ns' doesn't exist) error in ldpred gibbs 

### ISSUE THREAD

**Issue by annashcherbina** [bvilhjal/ldpred#143]
running LDpred v. 1.0.11

command: 
```
ldpred gibbs --cf step1_CES.EUR --ldr 2300 --ldf ld_CES_EUR  --out step2_CES_EUR --N 446696
```

Getting this error:
```
Calculating LD information w. radius 2300
Storing LD information to compressed pickle file
Applying LDpred with LD radius: 2300
4917800 SNP effects were found
Calculating LDpred-inf weights

Starting LDpred gibbs with f=1.0000
Traceback (most recent call last):
  File "/users/annashch/miniconda3/bin/ldpred", line 10, in <module>
    sys.exit(main())
  File "/users/annashch/miniconda3/lib/python3.7/site-packages/ldpred/run.py", line 380, in main
    main_with_args(sys.argv[1:])
  File "/users/annashch/miniconda3/lib/python3.7/site-packages/ldpred/run.py", line 364, in main_with_args
    LDpred_gibbs.main(p_dict)
  File "/users/annashch/miniconda3/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py", line 416, in main
    sampl_var_shrink_factor=1, verbose=p_dict['debug'], summary_dict=summary_dict)
  File "/users/annashch/miniconda3/lib/python3.7/site-packages/ldpred/LDpred_gibbs.py", line 296, in ldpred_genomewide
    ns = g['ns'][...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper 
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper 
  File "/users/annashch/miniconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper 
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper 
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'ns' doesn't exist)"
```
Any thoughts? 
Thank you for your help!

**Comment by kristil2** [comment]
Hi! Did you ever solve the issue? I´m having the same problem, weirdly, for files the same line of code works, for some not, but cannot figure out, what is the difference.

**Comment by annashcherbina** [comment]
I got around the issue as follows. 

modify this line in the source code: 

https://github.com/bvilhjal/ldpred/blob/master/ldpred/LDpred_gibbs.py#L296 

change this: 
```
ns = g['ns'][...] 
```
to this: 
```
ns=None
```
This should work fine as long as you are providing the N parameter (sample size) when you call the code. I don't believe this ns variable is used downstream for anything, so setting it to None appears to resolve the issue.
