### ISSUE TITLE
KeyError: "Unable to open object (object 'cord_data' doesn't exist)"

### ISSUE THREAD

**Issue by bbitarello** [bvilhjal/ldpred#146]
Hello,
I ran the coordination step and it appeared to have worked. However, when I try ldpred gibbs or ldpred p+t I get the error:

KeyError: "Unable to open object (object 'cord_data' doesn't exist)"

I ran coord as:

`ldpred coord \
    --rs SNP \
    --A1 A1 \
    --A2 A2 \
    --pos POS \
    --chr CHR \
    --pval PVAL \
    --eff BETA \
    --ssf-format CUSTOM \
    --eff_type LINREG\
    --N 360388 \
    --vgf JHS.ldpred \
    --ssf Height.QC.gz \
    --out JHS.coord \
    --gf 1000g_all `

and got no error message. The log file from that looks like:

`== LDpred v. 1.0.10 ======

Parsing summary statistics file: /home/bbita/height_prediction/ldpred/output/Height.QC.gz
SS file loaded, now sorting and storing in HDF5 file.
Coordinating datasets (Summary statistics, LD reference genotypes, and Validation genotypes).`

#JHS.ldpred and 1000g_all are prefixes for .bim/.bed/.fam files

I have I am running out of ideas. Any help appreciated!
Thank you.

**Comment by bbitarello** [comment]
I should clarify that my ldpred coord command is the following:

`ldpred gibbs  --cf JHS.coord --ldr 232 --ldf JHS.ld --out JHS.weight`

and error:

========== LDpred v. 1.0.10 ===============================

Calculating LD information w. radius 232
Traceback (most recent call last):
  File "/home/bbita/ENV/bin/ldpred", line 8, in <module>
    sys.exit(main())
  File "/home/bbita/ENV/lib/python3.6/site-packages/ldpred/run.py", line 337, in main
    main_with_args(sys.argv[1:])
  File "/home/bbita/ENV/lib/python3.6/site-packages/ldpred/run.py", line 323, in main_with_args
    LDpred_gibbs.main(p_dict)
  File "/home/bbita/ENV/lib/python3.6/site-packages/ldpred/LDpred_gibbs.py", line 413, in main
    ld_dict = ld.get_ld_dict_using_p_dict(p_dict, summary_dict)
  File "/home/bbita/ENV/lib/python3.6/site-packages/ldpred/ld.py", line 247, in get_ld_dict_using_p_dict
    summary_dict=summary_dict)
  File "/home/bbita/ENV/lib/python3.6/site-packages/ldpred/ld.py", line 277, in get_ld_dict
    cord_data_g = df['cord_data']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/bbita/ENV/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'cord_data' doesn't exist)"

**Comment by bbitarello** [comment]
For some reason the coordinations step doesn't finish, it just ends, and it doesn't give an error. SO because coord is not completed, ldpred gibbs doesn't find the coord file, even though it exists (but wasn't written till the end). Does this make sense?

**Comment by bbitarello** [comment]
I think this happened because the job ran out of memory.
