### ISSUE TITLE
KeyError: 'CT'

### ISSUE THREAD

**Issue by marine11** [bvilhjal/ldpred#147]
HI,
An error occurred during the 3-step SCORE process.
--------------------------------------------------
Calculating LDpred-inf risk scores
0.43%Traceback (most recent call last):
  File "/Anaconda/bin/ldpred", line 10, in <module>
    sys.exit(main())
  File "/Anaconda/lib/python3.7/site-packages/ldpred/run.py", line 337, in main
    main_with_args(sys.argv[1:])
  File "/Anaconda/lib/python3.7/site-packages/ldpred/run.py", line 329, in main_with_args
    validate.main(p_dict)
  File "/Anaconda/lib/python3.7/site-packages/ldpred/validate.py", line 674, in main
    verbose=verbose, summary_dict=summary_dict)
  File "/Anaconda/lib/python3.7/site-packages/ldpred/validate.py", line 409, in calc_risk_scores
    prs_dict = get_prs(bed_file, rs_id_map, phen_map, only_score=only_score, verbose=verbose)
  File "/data/sskimvd/Anaconda/lib/python3.7/site-packages/ldpred/validate.py", line 100, in get_prs
    [util.opp_strand_dict[g_nt[0]], util.opp_strand_dict[g_nt[1]]])
KeyError: 'CT'
-----------------------------------------------

What is the problem?
Thank you.

**Comment by pablogargon** [comment]
Hi, I have the same problem. It seems to be related with flipping variants. When I use the LD reference as validation dataset the error does not appear. I still don't know how to fix it though, maybe I will try manually flipping the alleles and see if the error dissapears.
