### ISSUE TITLE
Lowercase genotype causes "SNPs excluded due to non-matching nucleotides"

### ISSUE THREAD

**Issue by eldronzhou** [bvilhjal/ldpred#4]
Hi,

I encountered an error when running ldpred on my dataset. Below is my log file. 

`(python2) [gz222@c18n04 ldpred_data]$ coord --gf=../rawdata/hdl_eur/hdl_eur --ssf=./jointGwasMc_HDL.txt --N=99900 --ssf_format GIANT2 --out out`

```
Preparing to parse summary statistics
Parsing SNP list
Parsing bim file: ../rawdata/hdl_eur/hdl_eur.bim
24680
Parsing the file: ./jointGwasMc_HDL.txt
MarkerName      Allele1 Allele2 Freq.A1.1000G.EUR       b       SE      p       N

SS file loaded, now sorting and storing in HDF5 file.
2379 SNPs on chromosome 1
Still 2379 SNPs on chromosome 1
1865 SNPs on chromosome 2
Still 1865 SNPs on chromosome 2
1437 SNPs on chromosome 3
Still 1437 SNPs on chromosome 3
991 SNPs on chromosome 4
Still 991 SNPs on chromosome 4
1247 SNPs on chromosome 5
Still 1247 SNPs on chromosome 5
1607 SNPs on chromosome 6
Still 1607 SNPs on chromosome 6
1208 SNPs on chromosome 7
Still 1208 SNPs on chromosome 7
905 SNPs on chromosome 8
Still 905 SNPs on chromosome 8
1066 SNPs on chromosome 9
Still 1066 SNPs on chromosome 9
1219 SNPs on chromosome 10
Still 1219 SNPs on chromosome 10
1534 SNPs on chromosome 11
Still 1534 SNPs on chromosome 11
1361 SNPs on chromosome 12
Still 1361 SNPs on chromosome 12
525 SNPs on chromosome 13
Still 525 SNPs on chromosome 13
842 SNPs on chromosome 14
Still 842 SNPs on chromosome 14
908 SNPs on chromosome 15
Still 908 SNPs on chromosome 15
917 SNPs on chromosome 16
Still 917 SNPs on chromosome 16
1258 SNPs on chromosome 17
Still 1258 SNPs on chromosome 17
451 SNPs on chromosome 18
Still 451 SNPs on chromosome 18
1406 SNPs on chromosome 19
Still 1406 SNPs on chromosome 19
694 SNPs on chromosome 20
Still 694 SNPs on chromosome 20
315 SNPs on chromosome 21
Still 315 SNPs on chromosome 21
545 SNPs on chromosome 22
Still 545 SNPs on chromosome 22
24680 SNPs parsed from summary statistics file.
Loaded 3337 controls and 153 cases
Genotype dictionary filled
Working on chromsome: chrom_1
Found 2379 SNPs present in both datasets
0 SNPs were excluded due to ambiguous nucleotides.
2379 SNPs were excluded due to non-matching nucleotides.
Iterating over file to load SNPs
Traceback (most recent call last):
  File "/ysm-gpfs/home/gz222/software/anaconda3/envs/python2/bin/coord", line 11, in <module>
    sys.exit(main())
  File "/ysm-gpfs/home/gz222/software/anaconda3/envs/python2/lib/python2.7/site-packages/ldpred/coord_genotypes.py", line 1824, in main
    hdf5_file=h5f, min_maf=p_dict['maf'], skip_coordination=p_dict['skip_coordination'])
  File "/ysm-gpfs/home/gz222/software/anaconda3/envs/python2/lib/python2.7/site-packages/ldpred/coord_genotypes.py", line 1280, in coordinate_genot_ss
    raw_snps, freqs = _parse_plink_snps_(genotype_file, snp_indices)
  File "/ysm-gpfs/home/gz222/software/anaconda3/envs/python2/lib/python2.7/site-packages/ldpred/coord_genotypes.py", line 190, in _parse_plink_snps_
    next_i = ordered_snp_indices.pop()
IndexError: pop from empty list
```
If I understand correctly, the error is caused by nucleotides of all SNPs on chr1 differ in GWAS summary stats file and LD reference genotype file. I look at some SNPs on chr1 in these two files.

The first line of bim file is:
`1       rs3737728       0       1021415 a       g`

And the corresponding SNPs in GWAS summary stats file is 
`rs3737728       a       g       0.2797  9e-4    0.0062  0.5509  89209`

It seems that  nucleotides of this SNP are same in two files. So I'm really confused on what caused the error?

Thanks,
Geyu

**Comment by eldronzhou** [comment]
I found the problem after checking the code.


```
g_nt = [g_nts[g_i][0], g_nts[g_i][1]]
    
if (not g_nt[0] in valid_nts) or (not g_nt[1] in valid_nts):
    num_non_matching_nts += 1
    tot_num_non_matching_nts += 1                
    continue
```

The genotypes in my bim file are all in lower case, which are not in `valid_nts = set(['A', 'T', 'C', 'G'])`. The problem is fixed if changing `g_nt = [g_nts[g_i][0], g_nts[g_i][1]]` to `g_nt = [g_nts[g_i][0].upper(), g_nts[g_i][1].upper()]`.

**Comment by bvilhjal** [comment]
Hi, 

I'm sorry about the slow response, but it's great that you discovered the issue.  If you have any other issues, let me know. 

Best,
Bjarni
