### ISSUE TITLE
global name 'non_zero_chromosomes' is not defined

### ISSUE THREAD

**Issue by gmgaous** [bvilhjal/ldpred#41]
Hi Bjarni,
I downloaded the ldpred about one month ago (version 0.9.9). I am trying to run the validate script with

validate --vgf=./Olopade_chr1.imputed_common_SUMstat_newID 
--rf=./OUTPUT_pruning 
--out=./OUTPUT_validate_pruning 
--res_format=P+T

I get the an error similar to one posted before (see below). 

Calculating P+T risk scores using p-value threshold of 1.000e+00
Traceback (most recent call last):
  File "/home/ggao5/.conda/envs/myPython2.7/bin/validate", line 11, in <module>
    sys.exit(main())
  File "/home/ggao5/.conda/envs/myPython2.7/lib/python2.7/site-packages/ldpred/validate.py", line 735, in main
    rs_id_map = parse_pt_res(weights_file)
  File "/home/ggao5/.conda/envs/myPython2.7/lib/python2.7/site-packages/ldpred/validate.py", line 400, in parse_pt_res
    non_zero_chromosomes.add(chrom)
NameError: global name 'non_zero_chromosomes' is not defined

Guimin

**Comment by bvilhjal** [comment]
Hi, thanks for reporting this.  I believe this has been fixed in the latest version.
