### ISSUE TITLE
coord -- UnboundLocalError: local variable 'prs' referenced before assignment

### ISSUE THREAD

**Issue by privefl** [bvilhjal/ldpred#44]
[Data to reproduce the issue](https://www.dropbox.com/sh/oeib5upze912qza/AACj582B2DYMjXnUUDumjzIIa?dl=0)

```
python3 ../ldpred/LDpred.py coord --gf reprex --ssf SUM_STATS_FILE.txt --ssf-format BASIC --N 12000 --out OUT_COORD_FILE.hdf5
Preparing to parse summary statistics
Parsing bim file: reprex.bim
Parsing the file: SUM_STATS_FILE.txt
Ignored chromosomes: 9chrc
Please note that only data on chromosomes 1-23, and X is parsed.
SS file loaded, now sorting and storing in HDF5 file.
Parsed summary stats for 21540 SNPs on chromosome 1
Parsed summary stats for 23119 SNPs on chromosome 2
In all, 44659 SNPs parsed from summary statistics file.
Loaded 1129 controls and 451 cases
Genotype dictionary filled
Working on chromsome: chrom_1
Iterating over file to load SNPs
21540 SNPs were retained on chromosome 1.
Verifying coordinated data
Now storing coordinated data to HDF5 file.
Traceback (most recent call last):
  File "../ldpred/LDpred.py", line 245, in <module>
    main()
  File "../ldpred/LDpred.py", line 230, in main
    coord_genotypes.main(p_dict)
  File "/home/privef/Bureau/ldpred/ldpred/coord_genotypes.py", line 728, in main
    debug=p_dict['debug'])
  File "/home/privef/Bureau/ldpred/ldpred/coord_genotypes.py", line 341, in coordinate_genot_ss
    risk_scores += prs
UnboundLocalError: local variable 'prs' referenced before assignment
```

```
python --version
Python 3.7.0
```

**Comment by bvilhjal** [comment]
Should be fixed now.  Thanks for reporting it.
