### ISSUE TITLE
NameError: global name 'non_zero_chromosomes' is not defined

### ISSUE THREAD

**Issue by brielin** [bvilhjal/ldpred#5]
While running the validate script with

validate \
    --vgf=... \
    --rf=... \
    --out=... \
    --res_format=P+T \
    --TS=0.01, 0.001

I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/validate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ldpred/validate.py", line 735, in main
    rs_id_map = parse_pt_res(weights_file)       
  File "/usr/local/lib/python2.7/dist-packages/ldpred/validate.py", line 400, in parse_pt_res
    non_zero_chromosomes.add(chrom)
NameError: global name 'non_zero_chromosomes' is not defined

**Comment by bvilhjal** [comment]
I finally fixed this.
