### ISSUE TITLE
coord_genotypes.py cannot find chromosome in SS dataset

### ISSUE THREAD

**Issue by hershwin** [bvilhjal/ldpred#58]
Hey Bjarni,

Thank you for updating the LDpred software!

I'm currently having trouble running the coord_genotypes.py. It is unable to find any chromosomes in the summary statistics file. In the previous version, I was able to do this perfectly fine. My data is currently in standard format and matches everything with the example ss file. 

This is what I have in the command line: 
`python3 LDpred.py coord --gf=chr1_sigsnps --ssf=ss.txt --N=300000 --ilist=groupA_ID.txt --out=chr_1 --ssf-format STANDARD`

Do you know what the issue could be? Thanks! 

Yixuan

**Comment by kateishim** [comment]
Hi Bjarni,

I am experiencing the same issue as Yixuan's. 
The error message appears as below. 

Traceback (most recent call last):
  File "/data1/ishim/GRS/ldpred/LDpred.py", line 267, in <module>
    main()
  File "/data1/ishim/GRS/ldpred/LDpred.py", line 252, in main
    coord_genotypes.main(p_dict)
  File "/data1/ishim/GRS/ldpred/ldpred/coord_genotypes.py", line 570, in main
    sum_stats_parsers.parse_sum_stats(h5f, p_dict, bimfile, summary_dict)
  File "/data1/ishim/GRS/ldpred/ldpred/sum_stats_parsers.py", line 67, in parse_sum_stats
    pos=p_dict['pos'], input_is_beta=p_dict['beta'], **ss_args)
  File "/data1/ishim/GRS/ldpred/ldpred/sum_stats_parsers.py", line 113, in parse_sum_stats_custom
    valid_sids.add()
TypeError: add() takes exactly one argument (0 given)

Thanks much for your help in advance. 
Kate

**Comment by bvilhjal** [comment]
Hi, 

I believe I fixed this now.  Sorry about that!

Best,
Bjarni
