### ISSUE TITLE
LDpred score does not give an error when it cannot find SNP weights file

### ISSUE THREAD

**Issue by babak-ra** [bvilhjal/ldpred#64]
When running LDpred score, it does not give an error when it cannot find SNP weights file, it just quits with no message.

Also, even when using `--only-score` with no phenotypes, it throws this error:

```
Traceback (most recent call last):
  File "./LDpred.py", line 274, in <module>
    main()
  File "./LDpred.py", line 267, in main
    validate.main(p_dict)
  File "/opt/ldpred-1.0.3/ldpred/validate.py", line 634, in main
    summary_dict[5.2]={'name':'LDpred_inf (unadjusted) Pearson R2:','value':'%0.4f'%res_dict['LDpred_inf']['pred_r2']}                                                                                                                    
KeyError: 'pred_r2'
```

**Comment by bvilhjal** [comment]
Thanks for this, I just committed a fix for this, and made a new release.

Cheers,
Bjarni
