### ISSUE TITLE
LDpred score error

### ISSUE THREAD

**Issue by babak-ra** [bvilhjal/ldpred#68]
When the debug flag is used in scoring, `LDpred.py --debug score`, it causes the following error:

```
Iterating over BED file to calculate risk scores.
Traceback (most recent call last):
  File "./LDpred.py", line 291, in <module>
    main()
  File "./LDpred.py", line 284, in main
    validate.main(p_dict)
  File "/opt/ldpred-1.0.5/ldpred/validate.py", line 642, in main
    verbose=verbose, summary_dict=summary_dict)
  File "/opt/ldpred-1.0.5/ldpred/validate.py", line 400, in calc_risk_scores
    prs_dict = get_prs(bed_file, rs_id_map, phen_map, only_score=only_score, verbose=verbose)
  File "/opt/ldpred-1.0.5/ldpred/validate.py", line 127, in get_prs
    print('%0.2f%% of genotype file read' % (100.0 * (min(float(loci_i) / (num_loci-1.0)))))
TypeError: 'float' object is not iterable
```

**Comment by bvilhjal** [comment]
I believe I fixed this now..
