### ISSUE TITLE
`pip install ldpred` does not install `LDpred.py` script

### ISSUE THREAD

**Issue by delocalizer** [bvilhjal/ldpred#87]
I'd like to run the `LDpred.py` script as described in the documentation but running `pip install ldpred` (with or without the `--user` flag) does not install anything called `LDpred.py` anywhere, which I verified by running `find` on the entire filesystem from `/` down. There _is_ a script called `ldpred` installed to `/usr/local/bin` but running it gives `ModuleNotFoundError: No module named 'LDpred'`.
 
I suggest that the pip distribution for 1.0.6 is broken, or at least inconsistent with what the documentation describes.

_Originally posted by @delocalizer in https://github.com/bvilhjal/ldpred/issues/86#issuecomment-493075196_

**Comment by nandobonf** [comment]
I am also getting the same error message.

**Comment by wagrob** [comment]
I have the same issue. Installed is only the previous version of LDpred where you have to run a separate script for every step (e.g. coord_genotypes.py). A workaround seems to be to download the new python scripts directly into your working library and call them from there.

**Comment by dagola** [comment]
Me to.

Using `pip`:
```
$ pip3 install --user ldpred 
Collecting ldpred
  Using cached https://files.pythonhosted.org/packages/b9/a1/427d7199a0961dc83e023d40cea0bf1295030c7ec4a0b77b60d99a42df0b/LDpred-1.0.6-py3-none-any.whl
Requirement already satisfied: h5py in /home/damian/.local/lib/python3.6/site-packages (from ldpred) (2.9.0)
Requirement already satisfied: plinkio in /home/damian/.local/lib/python3.6/site-packages (from ldpred) (0.9.7)
Requirement already satisfied: scipy in /home/damian/.local/lib/python3.6/site-packages (from ldpred) (1.3.0)
Requirement already satisfied: numpy>=1.7 in /home/damian/.local/lib/python3.6/site-packages (from h5py->ldpred) (1.16.4)
Requirement already satisfied: six in /home/damian/.local/lib/python3.6/site-packages (from h5py->ldpred) (1.12.0)
Installing collected packages: ldpred
Successfully installed ldpred-1.0.6
$ ldpred
Traceback (most recent call last):
  File "/home/damian/.local/bin/ldpred", line 6, in <module>
    from LDpred import main
ModuleNotFoundError: No module named 'LDpred'
```

Using `setup.py` from the repository:
```
$ git clone https://github.com/bvilhjal/ldpred.git
Cloning into 'ldpred'...
remote: Enumerating objects: 1035, done.
remote: Total 1035 (delta 0), reused 0 (delta 0), pack-reused 1035
Receiving objects: 100% (1035/1035), 61.05 MiB | 28.83 MiB/s, done.
Resolving deltas: 100% (736/736), done.
$ cd ldpred
$ python3 setup.py install --user
running install
running bdist_egg
running egg_info
creating LDpred.egg-info
writing LDpred.egg-info/PKG-INFO
writing dependency_links to LDpred.egg-info/dependency_links.txt
writing entry points to LDpred.egg-info/entry_points.txt
writing requirements to LDpred.egg-info/requires.txt
writing top-level names to LDpred.egg-info/top_level.txt
writing manifest file 'LDpred.egg-info/SOURCES.txt'
reading manifest file 'LDpred.egg-info/SOURCES.txt'
writing manifest file 'LDpred.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/ldpred
copying ldpred/LD_pruning_thres.py -> build/lib/ldpred
copying ldpred/LDpred_gibbs.py -> build/lib/ldpred
copying ldpred/LDpred_inf.py -> build/lib/ldpred
copying ldpred/__init__.py -> build/lib/ldpred
copying ldpred/coord_genotypes.py -> build/lib/ldpred
copying ldpred/ld.py -> build/lib/ldpred
copying ldpred/plinkfiles.py -> build/lib/ldpred
copying ldpred/reporting.py -> build/lib/ldpred
copying ldpred/sum_stats_parsers.py -> build/lib/ldpred
copying ldpred/util.py -> build/lib/ldpred
copying ldpred/validate.py -> build/lib/ldpred
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/LD_pruning_thres.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/LDpred_gibbs.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/LDpred_inf.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/__init__.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/coord_genotypes.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/ld.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/plinkfiles.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/reporting.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/sum_stats_parsers.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/util.py -> build/bdist.linux-x86_64/egg/ldpred
copying build/lib/ldpred/validate.py -> build/bdist.linux-x86_64/egg/ldpred
byte-compiling build/bdist.linux-x86_64/egg/ldpred/LD_pruning_thres.py to LD_pruning_thres.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/LDpred_gibbs.py to LDpred_gibbs.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/LDpred_inf.py to LDpred_inf.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/coord_genotypes.py to coord_genotypes.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/ld.py to ld.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/plinkfiles.py to plinkfiles.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/reporting.py to reporting.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/sum_stats_parsers.py to sum_stats_parsers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/util.py to util.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/ldpred/validate.py to validate.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying LDpred.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LDpred.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LDpred.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LDpred.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LDpred.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying LDpred.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
ldpred.__pycache__.util.cpython-36: module references __file__
creating dist
creating 'dist/LDpred-1.0.6-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing LDpred-1.0.6-py3.6.egg
creating /home/damian/.local/lib/python3.6/site-packages/LDpred-1.0.6-py3.6.egg
Extracting LDpred-1.0.6-py3.6.egg to /home/damian/.local/lib/python3.6/site-packages
Adding LDpred 1.0.6 to easy-install.pth file
Installing ldpred script to /home/damian/.local/bin

Installed /home/damian/.local/lib/python3.6/site-packages/LDpred-1.0.6-py3.6.egg
Processing dependencies for LDpred==1.0.6
Searching for plinkio==0.9.7
Best match: plinkio 0.9.7
Adding plinkio 0.9.7 to easy-install.pth file

Using /home/damian/.local/lib/python3.6/site-packages
Searching for scipy==1.3.0
Best match: scipy 1.3.0
Adding scipy 1.3.0 to easy-install.pth file

Using /home/damian/.local/lib/python3.6/site-packages
Searching for h5py==2.9.0
Best match: h5py 2.9.0
Adding h5py 2.9.0 to easy-install.pth file

Using /home/damian/.local/lib/python3.6/site-packages
Searching for numpy==1.16.4
Best match: numpy 1.16.4
Adding numpy 1.16.4 to easy-install.pth file
Installing f2py script to /home/damian/.local/bin
Installing f2py3 script to /home/damian/.local/bin
Installing f2py3.6 script to /home/damian/.local/bin

Using /home/damian/.local/lib/python3.6/site-packages
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /home/damian/.local/lib/python3.6/site-packages
Finished processing dependencies for LDpred==1.0.6
$ ldpred
Traceback (most recent call last):
  File "/home/damian/.local/bin/ldpred", line 11, in <module>
    load_entry_point('LDpred==1.0.6', 'console_scripts', 'ldpred')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'LDpred'
```
Calling `LDpred.py` from the repository directly:
```
$ python3 LDpred.py 

=============================== LDpred v. 1.0.6 ================================

usage: LDpred [-h] [--debug] {coord,gibbs,inf,p+t,score} ...

Typicial workflow:
    1. Use LDpred coord to parse summary statistics and genotypes 
       and coordinate data. See LDpred coord --help for further usage 
       description and options.

    2. Use LDpred gibbs|inf|p+t to obtain SNP weights for polygenic
       scoring using one or more methods. See LDpred gibbs|inf|p+t --help for 
       further usage description and options.

    3. Use LDpred score to calculate polygenic scores using SNP
       weights from previous step. See LDpred score --help for further usage 
       description and options.

Thank you for using LDpred!

18 March 2019 
(c) Bjarni J Vilhjalmsson: bjarni.vilhjalmsson@gmail.com

================================================================================

positional arguments:
  {coord,gibbs,inf,p+t,score}
                        Select ldpred action among the following options:
    coord               Parse and coordinate summary statistics and genotypes.
    gibbs               Estimate LDpred (Gibbs sampler) SNP weights. (Requires
                        a coordinated dataset.)
    inf                 Estimate LDpred-inf SNP weights. (Requires a
                        coordinated dataset.)
    p+t                 Obtain pruning+thresholding SNP weights. (Requires a
                        coordinated dataset.)
    score               Calculate polygenic scores using given SNP weights.

optional arguments:
  -h, --help            show this help message and exit
  --debug               Activate debugging mode (more verbose)
```

**Comment by bvilhjal** [comment]
I believe I've finally fixed this issue.  I apologize for the delay.  Please test it.

Best,
Bjarni
