### ISSUE TITLE
Chromosome header cannot be found in summary statistic file

### ISSUE THREAD

**Issue by OpenIDUser6** [bvilhjal/ldpred#89]
I run LDpred using test_data as:
LDpred.py coord --gf LDpred_cc_data_p0.001_train_0 --ssf LDpred_cc_data_p0.001_ss_0.txt --N 10000 --out test_ty --beta
But I got an error message:
=============================== LDpred v. 1.0.6 ================================

Parsing summary statistics file: LDpred_cc_data_p0.001_ss_0.txt
Traceback (most recent call last):
  File "/usr/local/apps/ldpred/1.0.6/bin/LDpred.py", line 300, in <module>
    main()
  File "/usr/local/apps/ldpred/1.0.6/bin/LDpred.py", line 285, in main
    coord_genotypes.main(p_dict)
  File "/usr/local/Anaconda/envs_app/ldpred/1.0.6/lib/python3.6/site-packages/ldpred/coord_genotypes.py", line 566, in main
    sum_stats_parsers.parse_sum_stats(h5f, p_dict, bimfile, summary_dict)
  File "/usr/local/Anaconda/envs_app/ldpred/1.0.6/lib/python3.6/site-packages/ldpred/sum_stats_parsers.py", line 73, in parse_sum_stats
    control_n=p_dict['control_n'], **ss_args)
  File "/usr/local/Anaconda/envs_app/ldpred/1.0.6/lib/python3.6/site-packages/ldpred/sum_stats_parsers.py", line 158, in parse_sum_stats_custom
    assert ch is None or ch in header_dict, 'Chromosome header cannot be found in summary statistic file'
AssertionError: Chromosome header cannot be found in summary statistic file

**Comment by OpenIDUser6** [comment]
prroblem solved by adding --ssf-format STANDARD
